Ch5 Use tesnsorflow kerass only works at google colab


1 Analyse sales data

2.1 Create dataset x=age_salary, y=purchased_list

2.2 find deviation with stdev of 1* *avr btw next item

In [57]:
!pip install onnx
!pip install onnx_tf
!pip install onnxscript

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 683.0/683.0 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.3/129.3 kB 8.5 MB/s eta 0:00:00


In [58]:
import numpy as np
import pandas as pd
import json
import requests
from google.colab import drive
from tensorflow import keras
from tensorflow.keras.models import load_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch
import torch.nn as nn
from torch.nn import functional as F
import torch.optim as optim
import onnx
import onnx_tf
import tensorflow_addons
print(tf.__version__)
sc=StandardScaler()
drive.mount('/content/drive')
f1 = pd.read_csv('/content/drive/MyDrive/ml/asset/sales2.csv')
print(f1.describe())
age_salary=f1.iloc[:,:-1].values
purchased_list=f1.iloc[:,-1].values
x_train, x_test, y_train, y_test = train_test_split(age_salary,purchased_list,test_size=.20,random_state=0)
x_train=sc.fit_transform(x_train)#80% of items are used for training
x_test=sc.transform(x_test)#20% of items are used for test

ImportError: cannot import name 'mapping' from 'onnx' (/usr/local/lib/python3.12/dist-packages/onnx/__init__.py)

5.1 Create base of neural network

5.2 Train the neural network

5.3 Find accuracy level by confusion matrix result:0.875


In [ ]:
model = keras.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


model.fit(x_train, y_train, epochs=50)
loss, accuracy =model.evaluate(x_test, y_test)
print(loss, accuracy)
model.summary()

Epoch 1/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.2440 - loss: 0.8406
Epoch 2/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5772 - loss: 0.6450
Epoch 3/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.7023 - loss: 0.5222
Epoch 4/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8221 - loss: 0.4266
Epoch 5/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8947 - loss: 0.3875
Epoch 6/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9362 - loss: 0.3029
Epoch 7/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9477 - loss: 0.2415
Epoch 8/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9590 - loss: 0.1956
Epoch 9/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9494 - loss: 0.1742
Epoch 10/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9505 - loss: 0.1569
Epoch 11/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9611 - loss: 0.1308
Epoch 12/50
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9564 - 

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_23 (Dense)                │ (None, 10)             │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_24 (Dense)                │ (None, 10)             │           110 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_25 (Dense)                │ (None, 2)              │            22 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 488 (1.91 KB)

 Trainable params: 162 (648.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 326 (1.28 KB)

5.4.1 way1 Find purchase rate with pytorch mannuary

In [ ]:
print(model.predict(sc.transform(np.array([[20,40000]])))[:,1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[0.00774065]


5.4.2 way2 create local file and estimate purchase rate

Create local file

In [ ]:
model.save('/content/drive/MyDrive/ml/asset/tfkerras_dataset.h5')

example1 age 40, salary 20000

example2 age 42, salary 50000

In [ ]:
f2=load_model('/content/drive/MyDrive/ml/asset/tfkerras_dataset.h5')
print(f2.predict(sc.transform(np.array([[20,40000]])))[:,1])
print(f2.predict(sc.transform(np.array([[42,50000]])))[:,1])


2.19.0


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 228ms/step
[0.00774065]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
[0.6996516]


In [ ]:
6. get data from server -> Bug at SSH env to open files

In [ ]:
request_data = json.dumps({"signature_name": "serving_default",
                   "instances": [[-1.43318661, -0.47466685],[0.2345214460208433, 0.03675871227617118]]
})
json_response = requests.post('http://35.238.92.68:8501/v1/models/customer_behavior_model:predict',request_data)
print (json_response.text)

4.1 Create base of neural network

4.2 Train the neural network

In [52]:
Xtrain_=torch.from_numpy(x_train).float()
Xtest_=torch.from_numpy(x_test).float()
ytrain_=torch.from_numpy(y_train)
ytest_=torch.from_numpy(y_test)
input_size=2
output_size=2
hidden_size=10
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)
   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)
       return F.log_softmax(X,dim=1)
model1 = Net() #mannual
optimizer = torch.optim.Adam(model1.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()
epochs = 100
for epoch in range(epochs):
  optimizer.zero_grad()
  Ypred = model1(Xtrain_)
  loss = loss_fn(Ypred,  ytrain_)
  loss.backward()
  optimizer.step()
#   print('Epoch',epoch, 'loss',loss.item())
# Epoch 0 loss 0.7977757453918457
# Epoch 1 loss 0.7583175897598267 ...
list(model1.parameters())

[Parameter containing:
 tensor([[ 0.6088,  0.6106],
         [ 0.4163,  1.0324],
         [ 0.4501,  0.3882],
         [ 1.0337, -0.0398],
         [-0.5467, -0.6656],
         [-0.2830,  0.9391],
         [ 0.1567, -0.2898],
         [-0.4830, -0.7559],
         [-0.4770, -0.3697],
         [ 1.2417,  0.2846]], requires_grad=True),
 Parameter containing:
 tensor([-0.3400,  0.7754,  0.2753,  0.1309,  0.0759,  0.4597, -0.7400,  0.1202,
          0.4524,  0.4658], requires_grad=True),
 Parameter containing:
 tensor([[ 0.2226, -0.0044,  0.2185,  0.6431,  0.0218,  0.6297, -0.3356, -0.3320,
          -0.2748,  0.4166],
         [ 0.2062,  0.2134,  0.8326,  0.8705, -0.3004,  0.8145,  0.2669, -0.1055,
           0.2082,  0.9460],
         [ 0.2090,  0.2943,  0.1815,  0.4093, -0.3154,  0.2745,  0.1742, -0.6601,
          -0.0146,  0.6285],
         [ 0.2868,  0.5571,  0.0551,  0.6239, -0.1696,  0.0917,  0.0023, -0.1520,
          -0.2849,  0.3787],
         [ 0.3518,  0.5002,  0.3405, -0.0407,

In [ ]:
torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()
y_cust_20_40000 = model1(torch.from_numpy(sc.transform(np.array([[40,20000]]))).float())
y_cust_20_40000
_, predicted_20_40000 = torch.max(y_cust_20_40000.data,-1)
predicted_20_40000
y_cust_42_50000 = model1(torch.from_numpy(sc.transform(np.array([[42,50000]]))).float())
y_cust_42_50000
_, predicted_42_50000 = torch.max(y_cust_42_50000.data,-1)
predicted_42_50000

7.1 use pytorch data > create dataset with .onnx

In [63]:
sample_tensor = torch.from_numpy(sc.transform(np.array([[40,20000]]))).float()
torch.onnx.export(model1,sample_tensor,'/content/drive/MyDrive/ml/asset/pt_dataset.onnx',export_params=True)

[torch.onnx] Obtain model graph for `Net([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `Net([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decomposition...
[torch.onnx] Run decomposition... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅


ONNXProgram(
    model=
        <
            ir_version=10,
            opset_imports={'': 20},
            producer_name='pytorch',
            producer_version='2.9.0+cu126',
            domain=None,
            model_version=None,
        >
        graph(
            name=main_graph,
            inputs=(
                %"x"<FLOAT,[1,2]>
            ),
            outputs=(
                %"log_softmax"<FLOAT,[1,2]>
            ),
            initializers=(
                %"fc1.weight"<FLOAT,[10,2]>{TorchTensor(...)},
                %"fc1.bias"<FLOAT,[10]>{TorchTensor<FLOAT,[10]>(Parameter containing: tensor([-0.3400,  0.7754,  0.2753,  0.1309,  0.0759,  0.4597, -0.7400,  0.1202, 0.4524,  0.4658], requires_grad=True), name='fc1.bias')},
                %"fc2.weight"<FLOAT,[10,10]>{TorchTensor(...)},
                %"fc2.bias"<FLOAT,[10]>{TorchTensor<FLOAT,[10]>(Parameter containing: tensor([ 0.4339, -0.0805,  0.3224,  0.2494,  0.0952,  0.3576,  0.3629, -0.3003, 0.4136,  0.4747]

example1 age 40, salary 20000 -> Bug

example2 age 42, salary 50000 -> Bug

In [62]:
from onnx_tf.backend import prepare
onnx_model = onnx.load('/content/drive/MyDrive/ml/asset/pt_dataset.onnx')
tf_rep = prepare(onnx_model)
prediction = tf_rep.run((sc.transform(np.array([[42,50000]]))))
prediction

ImportError: cannot import name 'mapping' from 'onnx' (/usr/local/lib/python3.12/dist-packages/onnx/__init__.py)